name: project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  font_awesome_flutter: ^10.5.0
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  mockito: ^5.4.2
  build_runner: ^2.4.6
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  image_picker: ^1.0.4
  http: ^0.13.6
  shimmer_animation: ^2.1.0+1
  webview_flutter: ^4.4.1
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^15.1.0+1
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.17.0
  appwrite: ^11.0.1
  shared_preferences: ^2.2.2

flutter:
  assets:
    - lib/aset/images/
    - lib/aset/icons/
  uses-material-design: true
